In [12]:
import torch

In [13]:
x = torch.randn(3)
x

tensor([ 0.0697, -1.0191, -0.2405])

In [14]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.4881,  1.1017, -0.2604], requires_grad=True)

In [15]:
y = x + 2
y

tensor([0.5119, 3.1017, 1.7396], grad_fn=<AddBackward0>)

In [16]:
z = y * y * 2
z

tensor([ 0.5240, 19.2407,  6.0527], grad_fn=<MulBackward0>)

In [19]:
z = z.mean()

In [20]:
z.backward()
x.grad

tensor([0.6825, 4.1356, 2.3195])

In [21]:
z = y * y * 2

In [23]:
v = torch.tensor([1., 1., 0.001], dtype=torch.float32)
z.backward(v)
x.grad

tensor([ 2.7299, 16.5422,  2.3265])

In [24]:
# x.requite_grad_(False)
# x.detach()
# with torch.no_grad()

In [26]:
x.requires_grad_(False)
x

tensor([-1.4881,  1.1017, -0.2604])

In [27]:
y = x.detach()
y

tensor([-1.4881,  1.1017, -0.2604])

In [29]:
with torch.no_grad():
    y = x + 2

In [30]:
y

tensor([0.5119, 3.1017, 1.7396])

In [41]:
weights = torch.ones(4, requires_grad=True)

In [42]:
for epoch in range(1):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])


In [43]:
for epoch in range(2):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
