In [2]:
import torch

In [4]:
t1 = torch.empty(1)
t1

tensor([4.3348e-35])

In [5]:
t2 = torch.empty(3, 4)
t2

tensor([[4.3349e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
t3 = torch.empty(3)
t3

tensor([4.3350e-35, 0.0000e+00, 3.3631e-44])

In [9]:
t4 = torch.ones(5)
t4

tensor([1., 1., 1., 1., 1.])

In [11]:
t5 = torch.ones(2, 3, dtype=torch.float32)
t5

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x

tensor([[0.1338, 0.4771],
        [0.1227, 0.8861]])

In [22]:
y

tensor([[0.2391, 0.5288],
        [0.9934, 0.5563]])

In [23]:
y.add_(x)
y

tensor([[0.3729, 1.0059],
        [1.1161, 1.4424]])

In [24]:
z = torch.mul(x, y)
z

tensor([[0.0499, 0.4799],
        [0.1370, 1.2781]])

In [25]:
d = torch.div(y, x)
d

tensor([[2.7871, 2.1085],
        [9.0934, 1.6278]])

In [26]:
x = torch.rand(4, 4)
x

tensor([[0.4020, 0.6159, 0.4957, 0.8003],
        [0.7140, 0.6064, 0.1495, 0.4098],
        [0.8538, 0.6246, 0.6223, 0.8459],
        [0.7831, 0.7013, 0.4395, 0.3084]])

In [29]:
y = x.view(16)
y

tensor([0.4020, 0.6159, 0.4957, 0.8003, 0.7140, 0.6064, 0.1495, 0.4098, 0.8538,
        0.6246, 0.6223, 0.8459, 0.7831, 0.7013, 0.4395, 0.3084])

In [30]:
z = x.view(-1, 8)
z

tensor([[0.4020, 0.6159, 0.4957, 0.8003, 0.7140, 0.6064, 0.1495, 0.4098],
        [0.8538, 0.6246, 0.6223, 0.8459, 0.7831, 0.7013, 0.4395, 0.3084]])

In [31]:
import numpy as np

In [32]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [34]:
b = a.numpy()
type(b)

numpy.ndarray

In [35]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [36]:
a.add_(a)
a

tensor([2., 2., 2., 2., 2.])

In [37]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [38]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [39]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1.], dtype=torch.float64)

In [40]:
a += 1
a

array([2., 2., 2., 2.])

In [41]:
b

tensor([2., 2., 2., 2.], dtype=torch.float64)

In [47]:
torch.cuda.is_available()

False