## `PyTorch`

An open source machine learning framework that accelerates the path from research prototyping to production deployment.

### `Installation`

for installation `PyTorch`, visit on [PyTorch](https://pytorch.org/).

### `Basic Tensors`

In [1]:
import torch
torch.cuda.is_available()

False

In [2]:
x = torch.empty(1)
print(x)

tensor([3.3631e-43])


Construct a 2x3 matrix, uninitialized:

In [3]:
x = torch.empty(2, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  9.1836e-39],
        [ 1.8856e+31, -1.3107e+05,  3.0794e-41]])


Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0272, 0.7271, 0.6857],
        [0.6333, 0.3645, 0.2032],
        [0.8823, 0.9443, 0.2597],
        [0.8030, 0.0306, 0.0729],
        [0.5130, 0.8995, 0.0217]])


<span style="color:blue">**Note :**</span>

`An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.`

Construct a matrix filled zeros and of dtype long:

In [5]:
x = torch.zeros(2, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [6]:
x = torch.tensor([5.7, 3])
print(x)

tensor([5.7000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(2, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3578,  1.9125, -0.9943],
        [-0.1305,  2.1681, -0.7611]])


Get the size:

In [8]:
print(x.size())

torch.Size([2, 3])


`torch.Size` is in fact a tuple, so it supports all tuple operations.

### `Operations`

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation. Let's see:

Additon: syntax 1

In [9]:
y = torch.rand(2, 3)
print(x + y)

tensor([[-0.1564,  2.0098, -0.4923],
        [ 0.5858,  3.0684,  0.0597]])


Addition: syntax 2

In [10]:
print(torch.add(x, y))

tensor([[-0.1564,  2.0098, -0.4923],
        [ 0.5858,  3.0684,  0.0597]])


Addition: providing an output tensor as argument

In [11]:
result = torch.empty(2, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1564,  2.0098, -0.4923],
        [ 0.5858,  3.0684,  0.0597]])


Addition: in-place

In [12]:
y.add_(x) # adds x to y
print(y)

tensor([[-0.1564,  2.0098, -0.4923],
        [ 0.5858,  3.0684,  0.0597]])


Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard NumPy-like indexing with all bells and whistles!

In [13]:
print(x[:, 1])

tensor([1.9125, 2.1681])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
print(x)
print(y)
print(z)

tensor([[ 0.3740, -0.1634,  0.3985, -0.2933],
        [-0.3878, -0.2381,  1.6460, -0.9038],
        [ 1.3047, -0.0679, -0.5279, -0.5152],
        [-0.6402, -1.0376, -0.0415, -0.6229]])
tensor([ 0.3740, -0.1634,  0.3985, -0.2933, -0.3878, -0.2381,  1.6460, -0.9038,
         1.3047, -0.0679, -0.5279, -0.5152, -0.6402, -1.0376, -0.0415, -0.6229])
tensor([[ 0.3740, -0.1634,  0.3985, -0.2933, -0.3878, -0.2381,  1.6460, -0.9038],
        [ 1.3047, -0.0679, -0.5279, -0.5152, -0.6402, -1.0376, -0.0415, -0.6229]])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1740])
-0.17402255535125732


#### `NumPy Bridge`

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.
#### `Converting a Torch Tensor to a NumPy Array`

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### `Converting NumPy Array to Torch Tensor`

See how changing the np array changed the Torch Tensor automatically

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.